# Generated by Django 4.2 on 2024-07-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email_service', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема сообщения')),
                ('date_dispatch', models.DateField(verbose_name='Дата отправки')),
                ('date_receipt', models.DateField(verbose_name='Дата получения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('mail_index', models.PositiveIntegerField(verbose_name='Уникальный индекс письма на почте')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_app', to='email_messages.mailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='email_messages.message', verbose_name='Сообщение')),
            ],
        ),
    ]
